In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(a.ndim)

2


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(2, 4)


In [ ]:
b = [1,2,3,4,5]
arr = np.array(b)
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(arr.dtype)

int64


In [ ]:
zz = np.zeros([3,4])

In [ ]:
zz

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zzz = np.full((3,3),7,dtype='complex')
zzz

array([[7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j]])

In [ ]:
rr = np.random.random((2,2))
rr

array([[0.65021259, 0.59112958],
       [0.90357066, 0.6644278 ]])

In [ ]:
f = np.arange(1,10,2)
f

array([1, 3, 5, 7, 9])

In [ ]:
lz = np.linspace(0,5,4)
lz

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [ ]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,8,1]])
arr

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 8, 1]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
newarr = arr.reshape(1,2,6)
newarr

array([[[1, 2, 3, 4, 5, 2],
        [4, 2, 1, 2, 8, 1]]])

In [ ]:
flarr = arr.flatten()
flarr

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 8, 1])

In [ ]:
arr = np.array([[-1,2,0,4],[4,--0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. ,  0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
temp = arr[:2,::2]
temp

array([[-1.,  0.],
       [ 4.,  6.]])

In [ ]:
temp = arr[1:3,::]
temp

array([[4. , 0.5, 6. , 0. ],
       [2.6, 0. , 7. , 8. ]])

In [ ]:
cond = arr > 2
temp = arr[cond]
temp

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

In [ ]:
a = np.array([[1,2,3],[3,4,5],[9,6,0]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 6, 0]])

In [ ]:
print(a.T)

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
print("Largest element is:", arr.max(axis = 1))

Largest element is: [4. 6. 8. 4.]


In [ ]:
print(a.max(axis = 0))

[9 6 5]


In [ ]:
print(a.cumsum(axis = 1))

[[ 1  3  6]
 [ 3  7 12]
 [ 9 15 15]]


In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
print(a,b)

print(np.vstack((c,b,a)))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 9 10]
 [11 12]
 [ 5  6]
 [ 7  8]
 [ 1  2]
 [ 3  4]]


In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
print(a,b)

print(np.vstack((a,c)))


[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]]


In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
print(a,b)

print(np.concatenate((a,b)))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
print(a,b)

print(np.concatenate((a,b,c)))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
a = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
np.hsplit(a,2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [ ]:
np.hsplit(a,3)

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]

In [ ]:
np.hsplit(a,6)

[array([[1],
        [2]]), array([[3],
        [4]]), array([[5],
        [6]]), array([[7],
        [8]]), array([[ 9],
        [10]]), array([[11],
        [12]])]

In [ ]:
np.hsplit(a,2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [ ]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [ ]:
import numpy as np

a = np.array([1.0,2.0,3.0])
b = 2.0
print(a*b)
c = [2.0,2.0,2.0]
print(a*c)


[2. 4. 6.]
[2. 4. 6.]


In [ ]:
import pandas as pd

In [ ]:
data = np.array(['Russel','Surya','ABD','GM'])

In [ ]:
ser = pd.Series(data,index = [10,20,30,40])
print(ser)

10    Russel
20     Surya
30       ABD
40        GM
dtype: object
